### ISSUE TITLE
Errors - first try

### ISSUE THREAD

**Issue by endoleg** [AndiBellstedt/WinEventLogCustomization#7]
Hi Andi! Great Module!

I have a administrative 
After Install-Module -Name WinEventLogCustomization (works!)
I use
New-WELCEventChannelManifest -ChannelFullName "AndiBellstedt/MyPersonalLog"
and i get some errors ... Any ideas? I use Windows 10, Powershell 5.1

Start-Process : Es wurde kein Parameter gefunden, der dem Parameternamen "WhatIf" entspricht.
In C:\Program Files\WindowsPowerShell\Modules\WinEventLogCustomization\1.0.2\WinEventLogCustomization.psm1:1469 Zeichen:17
-WhatIf:$false
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand
 
Expected temp file 'C:\Users\myuser1\AppData\Local\Temp\WELC_14088d6b-3798-4c6c-9332-def652ddbc9e\AndiBellstedt.h' is present, but has a too old timestamp. Something went wrong. Aborting process
In C:\Program Files\WindowsPowerShell\Modules\PSFramework\1.7.237\PSFramework.psm1:5421 Zeichen:23
if (-not $Cmdlet) { throw $records[0] }
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : WinEventLogCustomization_New-WELCEventChannelManifest

**Comment by AndiBellstedt** [comment]
Ok, I am able to reproduce.
Seams like, this is a Windows PowerShell (5.1.) issue. With PS7 the error does not occur.

I'll dig a little into that one. Sure, there will be support on PS7 and PS5 in parallel

**Comment by AndiBellstedt** [comment]
Fixed in Version 1.0.2.1
